// <auto-generated />
namespace HOL_Lab3_Latest_F.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Create : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Create));
        
        string IMigrationMetadata.Id
        {
            get { return "202211281623176_Create"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
